const images = [
  require('./../assets/icon.png'),
  require('./../assets/ic-add.png'),
  require('./../assets/ic-arrow-back.png'),
  require('./../assets/ic-button-graph-act.png'),
  require('./../assets/ic-button-graph-inact.png'),
  require('./../assets/ic-button-histogram-act.png'),
  require('./../assets/ic-button-histogram-inact.png'),
  require('./../assets/ic-button-pie-act.png'),
  require('./../assets/ic-button-pie-inact.png'),
  require('./../assets/ic-button-table-act.png'),
  require('./../assets/ic-button-table-inact.png'),
  require('./../assets/ic-clock.png'),
  require('./../assets/ic-exit.png'),
  require('./../assets/ic-favorites.png'),
  require('./../assets/ic-fon.png'),
  require('./../assets/ic-from-to.png'),
  require('./../assets/ic-geotag.png'),
  require('./../assets/ic-geotag2.png'),
  require('./../assets/ic-header.png'),
  require('./../assets/ic-menu.png'),
  require('./../assets/ic-placeholder-big.jpg'),
  require('./../assets/ic-placeholder-small.jpeg'),
  require('./../assets/ic-search.png'),
  require('./../assets/ic-tabbar-apteki-act.png'),
  require('./../assets/ic-tabbar-apteki-inact.png'),
  require('./../assets/ic-tabbar-data-act.png'),
  require('./../assets/ic-tabbar-data-inact.png'),
  require('./../assets/ic-tabbar-info-act.png'),
  require('./../assets/ic-tabbar-info-inact.png'),
  require('./../assets/ic-tabbar-monitor-act.png'),
  require('./../assets/ic-tabbar-monitor-inact.png'),
  require('./../assets/ic-unfavorites.png'),
  require('./../assets/test-apteka.png'),
];

export default images;
